import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class RequestData {
  final String code;
  final String type;
  final String typeDate;
  final IconData typeIcon;
  final String employeeName;
  final String employeeCode;
  final String employeeDept;
  final String period;
  final String company;
  final String branch;
  final String requestedAgo;
  final String status;

  const RequestData({
    required this.code,
    required this.type,
    required this.typeDate,
    required this.typeIcon,
    required this.employeeName,
    required this.employeeCode,
    required this.employeeDept,
    required this.period,
    required this.company,
    required this.branch,
    required this.requestedAgo,
    required this.status,
  });
}

final List<RequestData> dummyRequests = [
  const RequestData(
    code: '000001',
    type: 'Vacaciones',
    typeDate: '15/03/2025',
    typeIcon: LucideIcons.umbrella,
    employeeName: 'María Rodríguez',
    employeeCode: 'Código 001',
    employeeDept: 'Recepción',
    period: '01/04/2025 al 15/04/2025',
    company: 'Grupo Puntacana',
    branch: 'Puntacana Resort & Club',
    requestedAgo: 'hace 39 días',
    status: 'Pendiente',
  ),
  const RequestData(
    code: '000002',
    type: 'Cambio Alojamiento',
    typeDate: '10/03/2025',
    typeIcon: LucideIcons.bomb,
    employeeName: 'Luis Morales',
    employeeCode: 'Código 002',
    employeeDept: 'Mantenimiento',
    period: '01/04/2025 al N/A',
    company: 'Grupo Barceló',
    branch: 'Barceló Bávaro Palace',
    requestedAgo: 'hace 44 días',
    status: 'Aprobada',
  ),
  const RequestData(
    code: '000003',
    type: 'Uniformes',
    typeDate: '14/03/2025',
    typeIcon: LucideIcons.shirt,
    employeeName: 'Pedro Almonte',
    employeeCode: 'Código 003',
    employeeDept: 'Restaurante',
    period: 'N/A',
    company: 'Meliá Hotels',
    branch: 'Meliá Caribe Beach',
    requestedAgo: 'hace 40 días',
    status: 'Rechazada',
  ),
  const RequestData(
    code: '000004',
    type: 'Permiso',
    typeDate: '13/03/2025',
    typeIcon: LucideIcons.calendarClock,
    employeeName: 'Julia Hernández',
    employeeCode: 'Código 004',
    employeeDept: 'Spa',
    period: '20/03/2025 al 22/03/2025',
    company: 'AM Resorts',
    branch: 'Secrets Cap Cana',
    requestedAgo: 'hace 41 días',
    status: 'Pendiente',
  ),
  const RequestData(
    code: '000005',
    type: 'Licencia Médica',
    typeDate: '16/03/2025',
    typeIcon: LucideIcons.activity,
    employeeName: 'Roberto Sánchez',
    employeeCode: 'Código 005',
    employeeDept: 'Atención al Cliente',
    period: '18/03/2025 al 25/03/2025',
    company: 'Grupo Piñero',
    branch: 'Bahia Principe Grand La Romana',
    requestedAgo: 'hace 38 días',
    status: 'Aprobada',
  ),
  const RequestData(
    code: '000006',
    type: 'Vacaciones',
    typeDate: '12/03/2025',
    typeIcon: LucideIcons.umbrella,
    employeeName: 'Carlos Jiménez',
    employeeCode: 'Código 006',
    employeeDept: 'Cocina',
    period: '05/04/2025 al 20/04/2025',
    company: 'Hard Rock Hotels',
    branch: 'Hard Rock Punta Cana',
    requestedAgo: 'hace 42 días',
    status: 'Rechazada',
  ),
  const RequestData(
    code: '000007',
    type: 'Permiso',
    typeDate: '08/03/2025',
    typeIcon: LucideIcons.calendarClock,
    employeeName: 'Ana Martínez',
    employeeCode: 'Código 007',
    employeeDept: 'Administración',
    period: '15/03/2025 al 16/03/2025',
    company: 'Coral Hospitality',
    branch: 'Coral Hospitality Santo Domingo',
    requestedAgo: 'hace 46 días',
    status: 'Pendiente',
  ),
  const RequestData(
    code: '000008',
    type: 'Vacaciones',
    typeDate: '05/03/2025',
    typeIcon: LucideIcons.umbrella,
    employeeName: 'Jorge Pérez',
    employeeCode: 'Código 008',
    employeeDept: 'Seguridad',
    period: '10/04/2025 al 25/04/2025',
    company: 'RIU Hotels & Resorts',
    branch: 'RIU Palace Punta Cana',
    requestedAgo: 'hace 49 días',
    status: 'Aprobada',
  ),
  const RequestData(
    code: '000009',
    type: 'Licencia Médica',
    typeDate: '18/03/2025',
    typeIcon: LucideIcons.activity,
    employeeName: 'Laura Gómez',
    employeeCode: 'Código 009',
    employeeDept: 'Recepción',
    period: '20/03/2025 al 27/03/2025',
    company: 'Grupo Excellence',
    branch: 'Excellence Punta Cana',
    requestedAgo: 'hace 36 días',
    status: 'Rechazada',
  ),
  const RequestData(
    code: '000010',
    type: 'Uniformes',
    typeDate: '20/03/2025',
    typeIcon: LucideIcons.shirt,
    employeeName: 'Miguel Torres',
    employeeCode: 'Código 010',
    employeeDept: 'Restaurante',
    period: 'N/A',
    company: 'Grupo Iberostar',
    branch: 'Iberostar Selection Bávaro',
    requestedAgo: 'hace 34 días',
    status: 'Pendiente',
  ),
];
